CREATE TABLE ERS_USER_ROLES(
	ROLE_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	ROLE VARCHAR
);

CREATE TABLE ERS_USERS(
	USER_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	USERNAME VARCHAR UNIQUE NOT NULL,
	EMAIL VARCHAR UNIQUE NOT NULL,
	PASSWORD VARCHAR NOT NULL,
	GIVEN_NAME VARCHAR NOT NULL,
	SURNAME VARCHAR NOT NULL,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	ROLE_ID UUID NOT NULL,

	FOREIGN KEY (ROLE_ID) REFERENCES ERS_USER_ROLES (ROLE_ID)
);

CREATE TABLE ERS_REIMBURSEMENT_STATUSES(
	STATUS_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	STATUS VARCHAR
);

CREATE TABLE ERS_REIMBURSEMENT_TYPES(
TYPE_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
TYPE VARCHAR
);

CREATE TABLE ERS_REIMBURSEMENTS(
	REIMB_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	AMOUNT NUMERIC(6,2) NOT NULL,
	SUBMITTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	RESOLVED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DESCRIPTION VARCHAR NOT NULL ,
	AUTHOR_ID UUID NOT NULL ,
	RESOLVER_ID UUID,
	STATUS_ID UUID NOT NULL ,
	TYPE_ID UUID NOT NULL ,
	CONSTRAINT FK_AUTHOR_USER_ID
		FOREIGN KEY (AUTHOR_ID)
		REFERENCES ERS_USERS(USER_ID),
	CONSTRAINT FK_RESOLVER_USER_ID
		FOREIGN KEY (RESOLVER_ID)
		REFERENCES ERS_USERS(USER_ID),
	CONSTRAINT FK_REIMBURSEMENT_STATUS_ID
		FOREIGN KEY (STATUS_ID)
		REFERENCES ERS_REIMBURSEMENT_STATUSES(STATUS_ID),
	CONSTRAINT FK_REIMBURSEMENT_TYPE_ID
		FOREIGN KEY (TYPE_ID)
		REFERENCES ERS_REIMBURSEMENT_TYPES(TYPE_ID)
);
--------------------------------------------------------------------------------------------
SELECT *
FROM ers_users au
WHERE au.username = 'WINNIE' AND au.password = 'P4$$W0RD';

SELECT au.GIVEN_NAME, au.SURNAME, au.EMAIL, au.USERNAME, au.PASSWORD, au.role_id, ur.role
FROM ERS_USERS au
JOIN ERS_USER_ROLES ur
ON au.role_id = ur.role_id
WHERE au.username = 'WINNIE' AND au.password = 'P4$$W0RD';
-------------------------------------------------------------------------------------------------

CREATE TABLE ERS_USER_ROLES(
	ROLE_ID VARCHAR PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	ROLE VARCHAR
);

CREATE TABLE ERS_USERS(
	USER_ID VARCHAR PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	USERNAME VARCHAR UNIQUE NOT NULL,
	EMAIL VARCHAR UNIQUE NOT NULL,
	PASSWORD VARCHAR NOT NULL,
	GIVEN_NAME VARCHAR NOT NULL,
	SURNAME VARCHAR NOT NULL,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	ROLE_ID VARCHAR NOT NULL,

	FOREIGN KEY (ROLE_ID) REFERENCES ERS_USER_ROLES (ROLE_ID)
);

CREATE TABLE ERS_REIMBURSEMENT_STATUSES(
	STATUS_ID VARCHAR PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	STATUS VARCHAR
);

CREATE TABLE ERS_REIMBURSEMENT_TYPES(
TYPE_ID VARCHAR PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
TYPE VARCHAR
);

INSERT INTO ERS_REIMBURSEMENT_TYPES (TYPE)
VALUES ('LODGING'),
		('TRAVEL'),
		('FOOD'),
		('OTHER');

CREATE TABLE ERS_REIMBURSEMENTS(
	REIMB_ID VARCHAR PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	AMOUNT NUMERIC(6,2) NOT NULL,
	SUBMITTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	RESOLVED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DESCRIPTION VARCHAR NOT NULL,
	AUTHOR_ID VARCHAR NOT NULL ,
	RESOLVER_ID VARCHAR NOT NULL,
	STATUS_ID VARCHAR NOT NULL,
	TYPE_ID VARCHAR NOT NULL,
	CONSTRAINT FK_AUTHOR_USER_ID
		FOREIGN KEY (AUTHOR_ID)
		REFERENCES ERS_USERS(USER_ID),
	CONSTRAINT FK_RESOLVER_USER_ID
		FOREIGN KEY (RESOLVER_ID)
		REFERENCES ERS_USERS(USER_ID),
	CONSTRAINT FK_REIMBURSEMENT_STATUS_ID
		FOREIGN KEY (STATUS_ID)
		REFERENCES ERS_REIMBURSEMENT_STATUSES(STATUS_ID),
	CONSTRAINT FK_REIMBURSEMENT_TYPE_ID
		FOREIGN KEY (TYPE_ID)
		REFERENCES ERS_REIMBURSEMENT_TYPES(TYPE_ID)
);







