CREATE TABLE ERS_REIMBURSEMENTS(
	REIMB_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
	AMOUNT NUMERIC (6,2),
	SUBMITTED TIMESTAMP,
	RESOLVED TIMESTAMP,
	DESCRIPTION VARCHAR,
	AUTHOR_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
	RESOLVER_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
	STATUS_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
	TYPE_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),

 CONSTRAINT ERS_REIMBURSEMENTS_PK,
 PRIMARY KEY (ID)
);

CREATE TABLE ERS_REIMBURSEMENT_STATUSES(
STATUS_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
STATUS VARCHAR

 CONSTRAINT ERS_REIMBURSEMENT_STATUSES_PK,
 PRIMARY KEY (ID)
);

CREATE TABLE ERS_REIMBURSEMENT_TYPES(
TYPE_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
TYPE VARCHAR
);

CREATE TABLE ERS_USERS(
USERNAME VARCHAR,
EMAIL VARCHAR,
PASSWORD VARCHAR,
GIVEN_NAME VARCHAR,
SURNAME VARCHAR,
IS_ACTIVE BOOLEAN,
ROLE_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),

CONSTRAINT ERS_USERS_PK,
PRIMARY KEY (ROLE_ID)
FOREIGN KEY (ROLE_ID) REFERENCES ERS_USERS (ID);
);

CREATE TABLE ERS_USER_ROLES(
ROLE_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
ROLE VARCHAR,

CONSTRAINT ERS_USER_ROLES_PK,
 PRIMARY KEY (ID)
FOREIGN KEY (ROLE_ID) REFERENCES ERS_USER_ROLES (ID);
);

CREATE TABLE ERS_REIMBURSEMENT_TYPES(
TYPE_ID VARCHAR PRIMARY KEY,
TYPE VARCHAR

);


